#!/bin/bash

INSTANCE=$(screen -li | grep metricbeat | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
    echo "Already running: $INSTANCE"
else
    mkdir -p /vagrant/logs

    screen -S metricbeat -d -m bash -l -c "su - vagrant -c \"LS_JAVA_OPTS='-Djava.net.preferIPv4Stack=true' metricbeat -c /vagrant/conf/metricbeat-$VM_NAME.yml > /vagrant/logs/metricbeat-$VM_NAME.log 2>&1\""
    echo "-----------------------------------------------------------------------------------------------------------"
    echo " => Started $VM_NAME - $VM_NODE_NAME - $VM_NODE_IP: $(screen -li | grep metricbeat | sed 's/\s/ /g')"
    echo "-----------------------------------------------------------------------------------------------------------"
fi
